name: nlp
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=20.1.0=py37h27cfd23_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py37heb32a55_1
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - cudatoolkit=11.1.1=h6406543_8
  - debugpy=1.4.1=py37h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - importlib-metadata=4.8.1=py37h06a4308_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.2.0=py37h06a4308_1
  - ipython=7.27.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py37h06a4308_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.1.0=h2733197_1
  - libuv=1.42.0=h7f98852_0
  - libwebp=1.2.0=h89dd481_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h5e8e339_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h219a48f_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.4.3=py37h06a4308_0
  - numexpr=2.7.3=py37h22e1b3c_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.3=py37h8c16a72_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py37h5aabda8_0
  - pip=21.0.1=py37h06a4308_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyhca03da5_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py37h7b6447c_0
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.8.0=py3.7_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=22.2.1=py37h295c915_1
  - readline=8.1=h27cfd23_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.9.4=py37h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.8.0=py37
  - torchvision=0.9.0=py37_cu111
  - tornado=6.1=py37h27cfd23_0
  - traitlets=5.1.0=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - bidict==0.21.3
    - blessings==1.7
    - charset-normalizer==2.0.6
    - click==8.0.1
    - filelock==3.3.0
    - gpustat==0.6.0
    - huggingface-hub==0.0.17
    - idna==3.2
    - joblib==1.0.1
    - nvidia-ml-py3==7.352.0
    - psutil==5.8.0
    - pysbd==0.3.4
    - pyyaml==5.4.1
    - regex==2021.9.30
    - requests==2.26.0
    - sacremoses==0.0.46
    - tokenizers==0.10.3
    - torchinfo==1.5.3
    - tqdm==4.62.3
    - transformers==4.11.2
    - urllib3==1.26.7
